config/routes.rb
Rails.application.routes.draw do

  # mount ForestLiana::Engine => '/forest'
  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'member/dashboard#dashboard'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get "more_infos",               to: redirect("http://www.cforgood.com/plus-dinfos/")

  get 'about',                    to: 'pages#about'
  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'charte_confidentialite',   to: 'pages#charte_confidentialite'
  get 'mentions_legales',         to: 'pages#mentions_legales'
  get 'info_business',            to: 'pages#info_business'
  get 'info_cause',               to: 'pages#info_cause'
  get 'faq',                      to: 'pages#faq'
  get 'faq_connect',              to: 'pages#faq_connect'
  get 'landing_business',         to: 'pages#landing_business'
  get 'landing_cause',            to: 'pages#landing_cause'
  put 'newsletter',               to: 'pages#newsletter'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:show, :update] do
      get "dashboard",  to: "dashboard#dashboard"
      get "profile",    to: "dashboard#profile"
      get "ambassador", to: "dashboard#ambassador"
      get "gift",       to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',  to: 'dashboard#dashboard'
      post 'impersonation', to: 'dashboard#set_impersonation'
      get "profile",    to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  namespace :asso do
    resources :causes, only: [:index, :show]
    get 'dashboard', to: 'dashboard#dashboard'
  end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @businesses = Business.active.joins(:perks).active.distinct.includes(:business_category)
    @addresses_id = []
    @businesses.each do |business|
      # @addresses_id << [business.id, 0] # BUSINESS MAIN ADDRESS
      business.addresses.shop.each do |address_shop|
        @addresses_id << [business.id, address_shop.id]
      end
      if business.itinerant
        business.addresses.active.today.each do |address_itinerant|
           @addresses_id << [business.id, address_itinerant.id]
        end
      end
    end
    @addresses_id.delete([]) # REMOVE WHEN NO ACTIVE RECORD ASSOCIATION
  end

  def show
    # save request.referer when logout access
    if !user_signed_in?
      session[:referer] = request.url
    else
      session.delete(:referer)
    end

    @business = Business.joins(:business_category).find(params[:id])
    @perk = @business.perks.find(params[:perk_id])

    if params[:address_id].to_i > 0
      @address = @business.addresses.find(params[:address_id])
      longitude = @address.longitude
      latitude = @address.latitude
    else
      longitude = @business.longitude
      latitude = @business.latitude
    end

    @geojson = {"type" => "FeatureCollection", "features" => []}

    @geojson["features"] << {
      "type": 'Feature',
      "geometry": {
        "type": 'Point',
        "coordinates": [longitude, latitude],
      },
      "properties": {
        "marker-symbol": @business.business_category.marker_symbol
      }
    }
    respond_to do |format|
      format.html
      format.json{render json: @geojson}
    end
  end
end

app/controllers/pro/businesses_controller.rb
class Pro::BusinessesController < Pro::ProController

  skip_after_action :verify_authorized

  def new
    if current_impersonation
      @error = "Vous essayez de créer un commerce, nous vous avons déconnecté de #{current_impersonation.name}"
    end
    session[:impersonate_id] = nil
    @business = Business.new
  end

  def create
    @business = current_business.businesses.build(business_params)
    @business.password = 'cforgood'
    if @business.save
      session[:impersonate_id] = @business.id
      redirect_to pro_business_profile_path(current_business)
    else
      @error = "Echec de la création du commerce"
      render :new
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :email, :city, :zipcode, :business_category_id)
  end
end

app/views/businesses/index.html.erb
<%= content_for(:title) do %>
  Bons Plans
<% end %>
<%= content_for(:description) do %>
  Découvrez notre liste de bons plans
<% end %>

<div class="container-fluid admin">
  <!-- Sub Menu Sidebar -->
  <%= render "member/dashboard/shared/sidebar" %>
  <!-- Content - Statistics -->
  <div class="dashboard dashboard-view-perks">
    <div class="mobile-menu-overlay hidden"></div>

    <%= render "components/menu/index_search_category" %>

    <div id="mixitup" class="container-perk-cards">
      <!-- <div id="perks-list"> -->

          <!-- <input class="search" placeholder="Search" /> -->

        <!-- <ul class="list"> -->
      <% @businesses.each do |business| %>
        <% (@addresses_id.select { |address_id| address_id[0] == business.id }).each do |address_id| %>
          <!-- COMPONENT | ADDRESSES -->
          <% business.perks.active.each do |perk| %>
                  <!-- <li> -->
            <!-- COMPONENT | CARD BON PLAN -->
            <%= link_to business_path(business, perk_id: perk.id, address_id: address_id[1]), class: "card-frame mix #{business.business_category_id} #{business.online? ? 'online' : ''}" do %>
              <!-- CARD HEADER -->
              <div class="card-header">
                <div class="card-header-main">
                  <span class="perk-title"><%= business.name %></span>
                  <% liked = Use.liked.where(perk_id: perk.id).count %>
                  <% if liked > 0 %>
                  <div class="perk-liked">
                    <%= render 'shared/icons/heart_like' %>
                    <span><%= liked %></span>
                  </div>
                  <% end %>
                </div>
                <div class="card-header-leader">
                <% if business.leader_picture.present? %>
                  <%= image_tag business.leader_picture.url(:avatar) %>
                <% else %>
                  <%= image_tag image_url 'default_pic.png' %>
                <% end %>
                </div>
                <div class="card-header-category" style="background-color: <%= business.business_category.color %>;">
                  <%= image_tag business.business_category.picture %>
                  <!-- <div class="category-container" style="background-color: <#= business.business_category.color %>;">
                  </div> -->
                </div>
              </div>
              <!-- CARD BODY -->
              <div class="card-body" style="background-image: url('<%= perk.picture.present? ? perk.picture.url(:card) : business.picture.url(:card) %>');">
                <div class="business-details">
                  <% if perk.flash? && perk.times > 0 %>
                    <span style="background-color: <%= business.business_category.color %>;"><i class="fa fa-flash"></i><%= perk.times - Use.used.where(perk_id: perk.id).count  %> restants</span>
                  <% end %>
                  <h3 class="perk-name"><%= perk.name %></h3>
                </div>
              </div>
            <% end %>
            <!-- END | CARD BON PLAN -->
          <% end %>
          <!-- END | ADDRESSES -->
        <% end %>
      <!-- </li> -->
      <% end %>
    <!-- </ul> -->
  <!-- </div> -->
    </div>

  <!-- END | DASHBOARD PERKS -->
  </div>
 <!-- END | ADMIN -->
</div>

<% content_for :after_js do %>
  <script>
    $(document).ready(function(){

      // TOOGLE CATEGORY MENUs
      $('#open-categories').click(function(event) {
        $('.search-category-overlay').toggleClass('hidden');
        // TOOGLE CATEGORY MENU
        $('.search-category').toggleClass('is-open-max');
        $('.category-item').toggleClass('is-open-min');
      });

      // TOOGLE CATEGORY OVERLAY
      $('.search-category-overlay').click(function(event) {
        $(this).addClass('hidden');
        $('.search-category').removeClass('is-open-max');
        $('.category-item').removeClass('is-open-min');
      });

      // EVENT AMPLITUDE USER_ALL_PERKS + USER_C_BUSINESS_ALLPERKS
      amplitude.logEvent('USER_ALL_PERKS');
      $('.card-frame').click(function(event) {
        amplitude.logEvent('USER_C_BUSINESS_ALLPERKS');
      });

    });

    var buttonFilter = {
    // Declare any variables we will need as properties of the object
    $filters: null,
    $reset: null,
    groups: [],
    outputArray: [],
    outputString: '',

    // The "init" method will run on document ready and cache any jQuery objects we will need.
    init: function(){
      var self = this; // As a best practice, in each method we will asign "this" to the variable "self" so that it remains scope-agnostic. We will use it to refer to the parent "buttonFilter" object so that we can share methods and properties between all parts of the object.

      self.$filters = $('#Filters');
      self.$reset = $('#categories-all');
      self.$container = $('#mixitup');
      self.$filters.find('fieldset').each(function(){
        self.groups.push({
          $buttons: $(this).find('.filter-btn'),
          active: ''
        });
      });
      self.bindHandlers();
    },

    // The "bindHandlers" method will listen for whenever a button is clicked.
    bindHandlers: function(){
      var self = this;

      // Handle filter clicks
      self.$filters.on('click', '.filter-btn', function(e){
        e.preventDefault();
        var $button = $(this);

        // If the button is active, remove the active class, else make active and deactivate others.
        $button.hasClass('is-selected') ?
          $button.removeClass('is-selected') :
          $button.addClass('is-selected').siblings('.filter-btn').removeClass('is-selected');

        self.parseFilters();
      });

      // Handle reset click
      self.$reset.on('click', function(e){
        e.preventDefault();
        self.$filters.find('.filter-btn').removeClass('is-selected');
        self.parseFilters();
      });
    },

    // The parseFilters method checks which filters are active in each group:
    parseFilters: function(){
      var self = this;

      // loop through each filter group and grap the active filter from each one.
      for(var i = 0, group; group = self.groups[i]; i++){
        group.active = group.$buttons.filter('.is-selected').attr('data-filter') || '';
      }

      self.concatenate();
    },

    // The "concatenate" method will crawl through each group, concatenating filters as desired:
    concatenate: function(){
      var self = this;

      self.outputString = ''; // Reset output string

      for(var i = 0, group; group = self.groups[i]; i++){
        self.outputString += group.active;
      }

      // If the output string is empty, show all rather than none:
      !self.outputString.length && (self.outputString = 'all');

      // Send the output string to MixItUp via the 'filter' method:
      if(self.$container.mixItUp('isLoaded')){
        self.$container.mixItUp('filter', self.outputString);
      }
    }
  };

    // On document ready, initialise our code.
    $(function(){
      // Initialize buttonFilter code
      buttonFilter.init();
      // Instantiate MixItUp
      $('#mixitup').mixItUp({
        controls: {
          enable: true // we won't be needing these
        },
        animationOptions: {
          duration: 750,
          easing: 'linear',
          queue: false
        }
      });
    });

    // var monkeyList = new List('perks-list', {
    //   valueNames: ['perk-name'],
    //   plugins: [ ListFuzzySearch() ]
    // });

    var options = {
      valueNames: [ 'perk-name' ]
    };

    var perksList = new List('perks-list', options);

  </script>
<% end %>

app/views/businesses/show.html.erb
<% content_for :meta_title, @business.name %>
<% content_for :meta_description, "Découvrez le Bon Plan offert par #{@business.name} !" %>
<% content_for :meta_image, @perk.picture.present? ? @perk.picture : @business.picture %>

<div class="container-fluid admin">
  <!-- Sub Menu Sidebar -->
  <%= render "member/dashboard/shared/sidebar" %>
  <!-- Content - Statistics -->
  <div class="dashboard dashboard-perk">
    <!-- OVERLY ON MENU ACTIVATION -->
    <div class="mobile-menu-overlay hidden"></div>
    <div class="side-menu-overlay hidden"></div>

    <% @perk.update_nb_view! if user_space? %>
    <div class="show-mobile">
      <!-- PERK MENU -->
      <div class="switch-tab">
        <span class="switch-active"></span>
        <button class="switch-button active-case">Bon plan</button>
        <button class="switch-button"><%= truncate(@business.name, length: 18) %></button>
      </div>

      <!-- PERK CARDS -->
      <div class="flip-container">
        <div class="flipper">
          <figure class="front">
          <!-- PERK IMAGE - CHANGE BACKGROUND IMAGE -->
          <% if @perk.picture.present? %>
            <div class="perk-image" style="background-image: url('<%= @perk.picture.url(:card) %>');">
          <% else %>
            <div class="perk-image" style="background-image: url('<%= @business.picture.url(:card) %>');">
          <% end %>

          <!-- IF FLASH PERK -->
          <% if @perk.flash? %>
            <% if @perk.times > 0 %>
              <span class="flash-notification" style="background-color: <%= @business.business_category.color %>;"><i class="fa fa-flash"></i><%= @perk.times - Use.used.where(perk_id: params[:perk_id]).count %> restants</span>
            <% end %>
            <span class="availabilities"><%= render(partial: "components/perk_flash_period", locals: { start_date: @perk.start_date, end_date: @perk.end_date }) %></span>
          <% end %>
          <h1><%= @perk.name %></h1>
          <p><%= @perk.description %></p>
            <div class="use-perk">
            <% if user_signed_in? %>
              <% if !@perk.perk_in_time? %>
                <div id="button-used">
                  <button class="empty">Bon plan non disponible</button>
                </div>
              <% elsif !@perk.perk_usable?(current_user) %>
                <div id="button-used">
                  <button class="empty">Bon plan épuisé</button>
                </div>
              <% else %>
                 <button type="button" class="use-button" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
              <% end %>
            <% else %>
              <button type="button" class="use-button-logout" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
              <%#= link_to "J'en profite", new_member_subscribe_path, class: "btn btn-use-button btn-block" %>
            <% end %>
          </div>
        </div>

        <div class="perk-owner">
          <div class="owner-details">
            <% if @business.leader_picture.present? %>
              <%= image_tag @business.leader_picture.url(:avatar) %>
            <% else %>
              <%= image_tag image_url 'default_pic.png' %>
            <% end %>
            <span>Rendez-vous chez <%= @business.name %></span>
          </div>
          <div id="map-perk" style="width: 100%;"></div>
          <span class="business-address"><i class="fa fa-map-marker"></i><%= @address.present? ? @address.street : @business.street %>, <%= @address.present? ? @address.zipcode : @business.zipcode %> <%= @address.present? ? @address.city : @business.city %></span>
        </div>
      </figure> <!-- END FRONT CARD -->

      <figure class="back"><!-- BACK CARD -->
        <div class="business-card">
          <!-- BACKGROUND IMAGE -->
          <div class="perk-image" style="background-image: url('<%= @business.picture.url(:card) %>');">
            <% if @business.leader_picture.present? %>

              <%= image_tag @business.leader_picture.url(:avatar) %>
            <% else %>
              <%= image_tag image_url 'default_pic.png' %>
            <% end %>
            <h1><%= @business.name %></h1>
          </div>

          <div class="profile-card">
            <div class="profile-business">
              <h3>En quelques mots</h3>
              <% if @business.description.present? %>
                <p><%= @business.description %></p>
              <% else %>
                <p>Profil en cours de construction</p>
              <% end %>
              <!-- LINKS | FIND THEM -->
              <%= render "pro/dashboard/shared/business_links" %>
            </div>
            <!-- SECOND SLIDE -->
            <div class="profile-owner">
              <h3>Qui se cache derrière ?</h3>
              <% if @business.leader_description.present? %>
                <p><%= @business.leader_description %></p>
              <% else %>
               <% if @business.leader_first_name.present? %>
                  <p>C'est <%= @business.leader_first_name %> qui se cache derrière. Lors de votre prochaine visite, rappelez-lui de raconter un peu son histoire !</p>
                <% else %>
                    <p>Profil en cours de construction</p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </figure><!-- END BACK CARD -->
    </div>
  </div>
</div><!-- END SHOW MOBILE -->

  <div class="show-desktop">
    <!-- COLUMN LEFT -->
    <div class="perk-details">
       <!-- BLOCK PERK -->
        <% if @perk.picture.present? %>
          <div class="perk-image" style="background-image: url('<%= @perk.picture %>');">
        <% else %>
          <div class="perk-image" style="background-image: url('<%= @business.picture %>');">
        <% end %>

        <!-- IF FLASH PERK -->
        <% if @perk.flash? %>
          <% if @perk.times > 0 %>
            <span class="flash-notification" style="background-color: <%= @business.business_category.color %>;"><i class="fa fa-flash"></i><%= @perk.times - Use.used.where(perk_id: params[:perk_id]).count %> restants</span>
          <% end %>
          <span class="availabilities"><%= render(partial: "components/perk_flash_period", locals: { start_date: @perk.start_date, end_date: @perk.end_date }) %></span>
        <% end %>
        <h1><%= @perk.name %></h1>
        <p><%= @perk.description %></p>
        <div class="use-perk">
          <% if user_signed_in? %>
            <% if !@perk.perk_in_time? %>
              <div id="button-used">
                <button class="empty">Bon plan non disponible</button>
              </div>
            <% elsif !@perk.perk_usable?(current_user) %>
              <div id="button-used">
                <button class="empty">Bon plan épuisé</button>
              </div>
            <% else %>
              <button type="button" class="use-button" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
            <% end %>
          <% else %>
            <button type="button" class="use-button-logout" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
            <%#= link_to "J'en profiterai bien", new_member_subscribe_path, class: "btn btn-use-button btn-block" %>
          <% end %>
        </div>
      </div>
      <!-- BLOCK MAP -->
      <div class="perk-map">
        <div id="map-perk-desktop" style="width: 100%;"></div>
        <span class="business-address"><i class="fa fa-map-marker"></i><%= @address.present? ? @address.street : @business.street %>, <%= @address.present? ? @address.zipcode : @business.zipcode %> <%= @address.present? ? @address.city : @business.city %></span>
      </div>
    </div>

    <!-- COLUMN RIGHT -->
    <div class="business-details">

      <div class="business-misc">
        <div class="perk-image" style="background-image: url('<%= @business.picture %>');">
          <% if @business.leader_picture.present? %>
            <%= image_tag @business.leader_picture.url(:avatar) %>
          <% else %>
            <%= image_tag image_url 'default_pic.png' %>
          <% end %>
          <h1><%= @business.name %></h1>
        </div>

        <div class="profile-card">
          <div class="profile-business">
            <h3>En quelques mots</h3>
            <% if @business.description.present? %>
              <p><%= @business.description %></p>
            <% else %>
              <p>Profil en cours de construction</p>
            <% end %>
          </div>
          <!-- SECOND SLIDE -->
          <div class="profile-owner">
            <h3>Qui se cache derrière ?</h3>
            <% if @business.leader_description.present? %>
              <p><%= @business.leader_description %></p>
            <% else %>
             <% if @business.leader_first_name.present? %>
                <p>C'est <%= @business.leader_first_name %> qui se cache derrière. Lors de votre prochaine visite, rappelez-lui de raconter un peu son histoire !</p>
              <% else %>
                  <p>Profil en cours de construction</p>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="business-contact">
          <%= render "pro/dashboard/shared/business_links" %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- MODAL CODE PERK -->
<% if user_signed_in? %>
  <% if !current_user.member %>
    <%= render "pro/perks/modals/perk_not_member" %>
  <% elsif Perk.find(params[:perk_id]).perk_detail.name == "email" %>
    <%= render "pro/perks/modals/perk_mailto" %>
  <% elsif @business.online %>
    <%= render "pro/perks/modals/perk_online" %>
  <% elsif device_type == :mobile %>
    <% if @address.present? %>
      <%= render "pro/perks/modals/perk_offline_mobile", latitude: @address.latitude, longitude: @address.longitude, street: @address.street, zipcode: @address.zipcode, city: @address.city %>
    <% else %>
      <%= render "pro/perks/modals/perk_offline_mobile", latitude: @business.latitude, longitude: @business.longitude, street: @business.street, zipcode: @business.zipcode, city: @business.city %>
    <% end %>
  <% else %>
    <% if @address.present? %>
      <%= render "pro/perks/modals/perk_offline_desktop", latitude: @address.latitude, longitude: @address.longitude, street: @address.street, zipcode: @address.zipcode, city: @address.city %>
    <% else %>
      <%= render "pro/perks/modals/perk_offline_desktop", latitude: @business.latitude, longitude: @business.longitude, street: @business.street, zipcode: @business.zipcode, city: @business.city %>
    <% end %>
  <% end %>
<% else %>
    <%= render "pro/perks/modals/perk_logout" %>
<% end %>

<% content_for(:after_js) do %>

  <script type="text/javascript">setRoutePathFromLocation()</script>

  <%= render 'components/map_show', geojson: @geojson, container: device_type == :mobile ? 'map-perk' : 'map-perk-desktop' %>

  <script>

    $('.switch-button').click(function() {
      $('.switch-active').toggleClass('activated');
      $('.flipper').toggleClass('flipped');
    });

    $(document).ready(function() {

      $(".use-button").click(function() {
        $('.use-overlay').removeClass('hidden');
        // EVENT AMPLITUDE USER_C_BENEFIT
        amplitude.logEvent('USER_C_BENEFIT');
      });

      $(".use-button-logout").click(function() {
        $('.use-overlay').removeClass('hidden');
        // EVENT AMPLITUDE USER_C_BENEFIT
        amplitude.logEvent('USER_C_BENEFIT_LOGOUT');
      });

      $(".btn-use-button").click(function() {
        // EVENT AMPLITUDE USER_C_BENEFIT
        amplitude.logEvent('USER_C_BENEFIT');
      });

      $(".close-button").click(function() {
        $('.use-overlay').addClass('hidden');
      });

      amplitude.logEvent('USER_SHOW_PERK');

    });

  </script>
<% end %>