config/routes.rb
Rails.application.routes.draw do

  # mount ForestLiana::Engine => '/forest'
  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'member/dashboard#dashboard'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get "more_infos",               to: redirect("http://www.cforgood.com/plus-dinfos/")

  get 'about',                    to: 'pages#about'
  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'charte_confidentialite',   to: 'pages#charte_confidentialite'
  get 'mentions_legales',         to: 'pages#mentions_legales'
  get 'info_business',            to: 'pages#info_business'
  get 'info_cause',               to: 'pages#info_cause'
  get 'faq',                      to: 'pages#faq'
  get 'faq_connect',              to: 'pages#faq_connect'
  get 'landing_business',         to: 'pages#landing_business'
  get 'landing_cause',            to: 'pages#landing_cause'
  put 'newsletter',               to: 'pages#newsletter'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:show, :update] do
      get "dashboard",  to: "dashboard#dashboard"
      get "profile",    to: "dashboard#profile"
      get "ambassador", to: "dashboard#ambassador"
      get "gift",       to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',  to: 'dashboard#dashboard'
      post 'impersonation', to: 'dashboard#set_impersonation'
      get "profile",    to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  namespace :asso do
    resources :causes, only: [:index, :show]
    get 'dashboard', to: 'dashboard#dashboard'
  end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/layouts/shared/_footer.html.erb
<div id="footer">
  <div class="col-xs-12 col-sm-2" id="logo-footer">
    <%=image_tag("logopouce.png") %>
  </div>
  <div class="col-xs-12 col-sm-2" id="footer-menu">
    <ul>
      <li class="footer-title">CforGood</li>
      <li><%= link_to "A propos", about_path %></li>
      <li><%= link_to "Notre charte", notre_charte_path %></li>
      <li><%= link_to "Contact", new_contact_form_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
      <!-- <li><a href="/notre_charte"><p>Presse</p></a></li> -->
    </ul>
  </div>
  <div class="col-xs-12 col-sm-2">
    <ul>
      <li class="footer-title">Communauté</li>
      <!--<li><a href="/notre_charte"><p>Nos Partenaires</p></a></li>-->
      <li><a class="typeform-share" href="https://cforgood1.typeform.com/to/iZ5QFx" data-mode="1" target="_blank"><p>Devenir Ambassadeur</p></a></li>
      <li><%= link_to "Vous êtes une entreprise", landing_business_path %></li>
      <li><%= link_to "Vous êtes une association", landing_cause_path %></li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-3">
    <ul>
      <li class="footer-title">Légal</li>
      <li><%= link_to "Conditions Générales", cgu_path %></li>
      <li><%= link_to "Charte De Confidentialité", charte_confidentialite_path %></li>
      <li><%= link_to "Mentions Légales", mentions_legales_path %></li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-3">
    <div class="col-xs-12" id="newsletter-footer">
      <li class="footer-title">Newsletter</li>
        <%= simple_form_for :newsletter, url:  newsletter_path, remote: true, method: :put do |f| %>
          <%= f.input :email, :label => false, :placeholder => "Email", :as => :email %>
          <%= f.button :submit, '>', class: "button button-turquoise" %>
        <% end %>
    </div>
    <div class="col-xs-12" id="social-media">
      <li class="footer-title">Suivez-Nous</li>
        <ul class="list-inline">
            <li>
              <a href="https://www.facebook.com/cforgood?fref=ts" class="link-contrast footer-icon-container-facebook" target="_blank">
                <i class="fa fa-facebook footer-icon"></i>
              </a>
            </li>

            <li>
              <a href="https://twitter.com/CforGood" class="link-contrast footer-icon-container-twitter" target="_blank">
                <i class="fa fa-twitter footer-icon"></i>
              </a>
            </li>

            <li>
              <a href="https://instagram.com/cforgood/" class="link-contrast footer-icon-container-instagram" target="_blank">
                <i class="fa fa-instagram footer-icon"></i>
              </a>
            </li>

            <li>
              <a href="https://fr.linkedin.com/company/cforgood" class="link-contrast footer-icon-container-linkedin" target="_blank">
                <i class="fa fa-linkedin footer-icon"></i>
              </a>
            </li>

        </ul>
    </div>
    <div class="row-space-top-2 col-xs-12">
      <h3>© CforGood 2016</h3>
    </div>
  </div>

    <div class="clear"></div>
    <div class="line-separator col-xs-12 col-sm-4 col-sm-offset-4"></div>
    <div class="clear"></div>
    <div class="text-center" id="sub-footer">
      <p>Réalisé avec <i class="fa fa-heart pl-5 pr-5"></i> à Bordeaux</p>
    </div>
    <div class="clear"></div>
</div>

app/views/layouts/shared/_head.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta name="apple-mobile-web-app-capable" content="yes">

<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- OneSignal -->

<link rel="manifest" href="/manifest.json">
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
<script>
  var OneSignal = OneSignal || [];
  <% if !Rails.env.development? %>
    OneSignal.push(["init", {
      appId: "<%= ENV['ONESIGNAL_APP_ID'] %>",
      safari_web_id: "<%= ENV['ONESIGNAL_SAFARI_WEB_ID'] %>",
      autoRegister: true,
      welcomeNotification: {
        "title": "CforGood",
        "message": "Merci pour votre inscription !",
        // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
      },
      notifyButton: {
        enable: false,/* Set to false to hide */
        text: {
          'tip.state.unsubscribed': 'Afficher les notifications',
          'tip.state.subscribed': 'Vous êtes abonné aux notifications',
          'tip.state.blocked': 'Vous avez bloqué les notifications',
          'message.prenotify': 'Cliquer pour accepter les notifications',
          'message.action.subscribed': 'Merci de nous suivre !',
          'message.action.resubscribed': 'Vous êtes inscrit aux notifications !',
          'message.action.unsubscribed': 'Vous ne recevrez plus de notifications',
          'dialog.main.title': 'Gérer les notifications',
          'dialog.main.button.subscribe': 'AUTORISER',
          'dialog.main.button.unsubscribe': 'BLOQUER',
          'dialog.blocked.title': 'Débloquer les notifications',
          'dialog.blocked.message': 'Suivez ces instructions pour autoriser les notifications :'
        },
      },
      promptOptions: {
        /* These prompt options values configure both the HTTP prompt and the HTTP popup. */
        /* actionMessage limited to 90 characters */
        actionMessage: "Nous aimerions vous envoyer nos dernières nouvelles et mises à jour.",
        /* acceptButtonText limited to 15 characters */
        acceptButtonText: 'AUTORISER',
        /* cancelButtonText limited to 15 characters */
        cancelButtonText: 'NON MERCI'
      }
    }]);
  <% else %>
    OneSignal.push(["init", {
      appId: "<%= ENV['ONESIGNAL_APP_ID'] %>",
      safari_web_id: "<%= ENV['ONESIGNAL_SAFARI_WEB_ID'] %>",
      autoRegister: true,
      subdomainName: 'cforgood',
      notifyButton: {
        enable: false,/* Set to false to hide */
        text: {
          'tip.state.unsubscribed': 'Afficher les notifications',
          'tip.state.subscribed': 'Vous êtes abonné aux notifications',
          'tip.state.blocked': 'Vous avez bloqué les notifications',
          'message.prenotify': 'Cliquer pour accepter les notifications',
          'message.action.subscribed': 'Merci de nous suivre !',
          'message.action.resubscribed': 'Vous êtes inscrit aux notifications !',
          'message.action.unsubscribed': 'Vous ne recevrez plus de notifications',
          'dialog.main.title': 'Gérer les notifications',
          'dialog.main.button.subscribe': 'AUTORISER',
          'dialog.main.button.unsubscribe': 'BLOQUER',
          'dialog.blocked.title': 'Débloquer les notifications',
          'dialog.blocked.message': 'Suivez ces instructions pour autoriser les notifications :'
        },
      },
      promptOptions: {
        /* These prompt options values configure both the HTTP prompt and the HTTP popup. */
        /* actionMessage limited to 90 characters */
        actionMessage: "Nous aimerions vous envoyer nos dernières actualités.",
        /* acceptButtonText limited to 15 characters */
        acceptButtonText: 'AUTORISER',
        /* cancelButtonText limited to 15 characters */
        cancelButtonText: 'NON MERCI'
      }
    }]);
  <% end %>
  // OneSignal.push(function() {
  // /* These examples are all valid */
  //   OneSignal.getUserId(function(userId) {
  //     console.log("OneSignal User ID:", userId);
  //     // (Output) OneSignal User ID: 270a35cd-4dda-4b3f-b04e-41d7463a2316
  //   });
  // });
</script>

<!-- Favicons -->
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'favicons/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'favicons/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'favicons/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'favicons/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'favicons/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'favicons/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'favicons/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'favicons/apple-touch-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'favicons/apple-touch-icon-180x180.png' %>">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-16x16.png' %>" sizes="16x16">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-96x96.png' %>" sizes="96x96">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-194x194.png' %>" sizes="194x194">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/android-chrome-192x192' %>" sizes="192x192">
<link rel="manifest" href="<%= image_path 'favicons/manifest.json' %>">
<link rel="shortcut icon" href="<%= image_path 'favicons/favicon.ico' %>">

<meta name="apple-mobile-web-app-title" content="CforGood">
<meta name="application-name" content="CforGood">
<meta name="theme-color" content="#ffffff">
<meta name="description" content="<%= meta_description %>">
<meta name="msapplication-TileColor" content="#347067">
<meta name="msapplication-TileImage" content="<%= image_path 'favicons/mstile-144x144.png' %>">
<meta name="msapplication-config" content="<%= image_path 'favicons/browserconfig.xml' %>">

<!-- Google Site Verification -->
<meta name="google-site-verification" content="l0XiovQqM1xIHH0sNA31AmubNQsVh9b-XrcL8OKr5J4" />

<!-- Open Graph FB -->
<meta property="og:title" content="<%= meta_title %>">
<meta property="og:type" content="website">
<meta property="og:description" content="<%= meta_description %>">
<meta property="og:url" content="<%= request.url %>">
<meta property="og:image" content="<%= image_url(meta_image) %>"/>
<meta property="og:site_name" content="<%= meta_title %>">

<!-- Twitter card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META[:twitter_account] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META[:twitter_account] %>">
<meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="<%= meta_title %>">
<meta itemprop="description" content="<%= meta_description %>">
<meta itemprop="image" content="<%= image_url(meta_image) %>">

<!-- MailChimp -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">

<!-- Mapbox GL -->
<link href='https://api.mapbox.com/mapbox-gl-js/v0.21.0/mapbox-gl.css' rel='stylesheet' />

<!-- Jquery -->
<link href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" >

<!-- AnimatedModal -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">

<!--  Select 2 -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">


<!-- Script for google analytics necessary in HEAD section -->
<%= render "layouts/shared/js/google_analytics" %>

<!-- Script for AMPLITUDE -->
<%= render "layouts/shared/js/amplitude" %>

<!-- Hotjar Tracking Code -->
<%= render "layouts/shared/js/hotjar" %>

<%= stylesheet_link_tag :application, media: "all" %>
<%= csrf_meta_tags %>

<!-- Wootric : survey -->
<%# if user_signed_in? || business_signed_in? %>
  <%#= render "layouts/shared/js/wootric" %>
<%# end %>

app/views/layouts/shared/_js.html.erb
<%= javascript_include_tag "application" %>

<!--  JQUERY & GOOGLE MAPS JS API -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
<script src="//cdn.jsdelivr.net/jquery.mixitup/latest/jquery.mixitup.min.js"></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>
<%= render "layouts/shared/js/jquery_validate_fr" %>

<!-- Bootsrap -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- Wootric : survey -->
<% if user_signed_in? || business_signed_in? %>
  <%= render "layouts/shared/js/wootric" %>
<% end %>

<!-- Mapbox GL -->
<script src='https://api.mapbox.com/mapbox-gl-js/v0.21.0/mapbox-gl.js'></script>

<!-- Algolia place -->
<script src="https://cdn.jsdelivr.net/places.js/1/places.min.js"></script>

<!-- Select2 : dropdown search -->
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

<!-- Geolocalisation -->
<script>getGeolocation()</script>

<!-- JS SCRIPTS -->
<%= render "layouts/shared/js/smooth_scroll" %>
<%= render "layouts/shared/js/typeform" %>
<%= render "layouts/shared/js/intercom" %>

app/views/layouts/shared/_navbar.html.erb
<!-- BANNER PROMO -->
<!-- remove class flash on #navbar if no banner %> -->
<%# if landing_page? %>
<!--   <div class="hidden-xs">
    <div class="container-fluid" id="banner-promo">
      <%#=link_to "http://www.kisskissbankbank.com/fr/projects/cforgood-la-revolution-positive", target: "_blank" do %>
        <div class="row text-center">
          <span>Financez la 1ère <strong>plateforme d'économie responsable et solidaire</strong> qui redonne le pouvoir d'agir et consommer dans le Bon Sens !</span>
          <i class="fa fa-chevron-circle-right"></i>
        </div>
      <%# end %>
    </div>
  </div> -->
<%# end %>
<!-- <div class="mobile-hidden"> -->

  <nav id="navbar" class="navbar nav <%= navbar_classes %>" role="navigation">
    <!-- ICON RESPONSIVE MENU -->
    <a href="#" class="menu-toggle">
      <div id="menu-icon">
        <span id="icon-line"></span>
        <span id="icon-line"></span>
        <span id="icon-line"></span>
        <span id="icon-line"></span>
      </div>
    </a>
    <!-- BRAND LOGO -->
    <!-- LOGO -->
    <% if user_signed_in? %>
      <%= link_to member_user_dashboard_path(current_user) do %>
        <div class="logo-desktop">
          <%= render "components/svg/logo" %>
        </div>
      <% end %>
    <% elsif business_signed_in? %>
      <%= link_to pro_business_dashboard_path(current_business) do %>
        <div class="logo-desktop">
          <%= render "components/svg/logo" %>
        </div>
      <% end %>
    <% else %>
      <%= link_to root_path do %>
        <div class="logo-desktop">
          <%= render "components/svg/logo" %>
        </div>
      <% end %>
    <% end %>

    <!-- MENU ITEMS -->
    <% if business_signed_in? && pro_space? && current_business.supervisor %>
      <%= render "components/select_impersonate_business", dropdown_search: "navbar_select_impersonate" %>
      <% if current_impersonation %>
        <div class="current-impersonation">
          Vous agissez en tant que <%= current_impersonation.name %>
        </div>
      <% end %>
    <% end %>

    <!-- MENU ITEMS -->
    <div class="link-container">
      <!-- PRO SIGN IN -->
      <% if business_signed_in? && pro_space? %>
        <div class="visible-xs menu-user-info">
          <% if current_business.picture.present? %>
            <%= image_tag avatar_url(current_business), class: "user-pic" %>
          <% else %>
            <%= image_tag "default_pic.png", class: "image-circle" %>
          <% end %>
          <span class="user-name">
            Bienvenue,<br> <%= current_business.name %>
          </span>
        </div>
        <ul>
          <li class="visible-xs">
            <%= link_to landing_business_path do %>
              <i class="fa fa-home"></i> <%= t(".how_it_works", default: "Accueil") %>
            <% end %>
          </li>
          <li class="faq-connect">
            <%= link_to faq_connect_path do %>
              <i class="fa fa-dot-circle-o"></i> <%= t(".how_it_works", default: "Aide et conseils") %>
            <% end %>
          </li>
          <li class="hidden-xs">
            <% if current_business.active %>
              <%= link_to pro_business_profile_path(current_business) do %>
                <% if current_business.picture.present? %>
                  <%= image_tag avatar_url(current_business), class: "img-circle", type: "button" %>
                <% else %>
                  <%= image_tag "default_pic.png", class: "img-circle", type: "button"  %>
                <% end %>
                <span class="user-name"><%= current_business.name %></span>
              <% end %>
            <% else %>
              <%= link_to pro_business_dashboard_path(current_business) do %>
                <% if current_business.picture.present? %>
                  <%= image_tag avatar_url(current_business), class: "img-circle", type: "button" %>
                <% else %>
                  <%= image_tag "default_pic.png", class: "img-circle", type: "button"  %>
                <% end %>
                <span class="user-name"><%= current_business.name %></span>
              <% end %>
            <% end%>
          </li>
        </ul>
      <!-- USER SIGN IN -->
      <% else %>
        <% if user_signed_in? && user_space? %>
          <div class="visible-xs menu-user-info">
            <% if current_user.picture.present? %>
              <%= image_tag avatar_url(current_user), class: "user-pic" %>
            <% else %>
              <%= image_tag "default_pic.png", class: "img-circle" %>
            <% end %>
            <span class="user-name">
              <% if current_user.last_name != "" && current_user.last_name != nil %>
                Bienvenue,<br> <%= current_user.first_name %> <%= current_user.last_name.chars.first + "." %>
              <% elsif current_user.name != "" && current_user.name != nil %>
                Bienvenue,<br> <%= current_user.name.split(" ")[0] %>
              <% end %>
            </span>
          </div>
          <ul>
            <li class="visible-xs">
              <%= link_to root_path do %>
                <i class="fa fa-home"></i> <%= t(".how_it_works", default: "Accueil") %>
              <% end %>
            </li>
            <!-- <li> -->
              <%#= link_to faq_connect_path do %>
                <!-- <i class="fa fa-dot-circle-o"></i> <%#= t(".how_it_works", default: "Aide et conseils") %> -->
              <%# end %>
            <!-- </li> -->
            <li class="user-profile-navbar mobile-dropdown">
              <% if current_user.active %>
                <a href="#">
                  <% if current_user.picture.present? %>
                    <%= image_tag avatar_url(current_user), class: "img-circle" %>
                  <% else %>
                    <%= image_tag "default_pic.png", class: "img-circle" %>
                  <% end %>
                  <i class="fa fa-angle-down"></i>
                </a>
                <!-- DESKTOP | OPEN MENU DROPDOWN -->
                <% if device_type != :mobile %>
                  <%= render "components/navbar_dropdown_profile" %>
                <% end %>
              <% else %>
                <%= link_to member_user_dashboard_path(current_user) do %>
                  <% if current_user.picture.present? %>
                    <%= image_tag avatar_url(current_user), class: "img-circle" %>
                  <% else %>
                    <%= image_tag "default_pic.png", class: "img-circle" %>
                  <% end %>
                    <% if current_user.last_name != "" && current_user.last_name != nil %>
                      <span class="user-name"><%= current_user.first_name %> <%= current_user.last_name.chars.first + "." %></span>
                    <% elsif current_user.name != "" && current_user.name != nil %>
                      <span class="user-name"><%= current_user.name.split(" ")[0]  %></span>
                    <% end %>
                <% end %>
              <% end %>
            </li>
          </ul>
        <!-- USER SIGN OUT -->
        <% else %>
          <ul>
            <% if asso_space? %>
              <li>
                <a href="https://cforgood1.typeform.com/to/PdisGd" data-mode="1" target="_blank">Devenir Partenaire</a>
              </li>
            <% elsif user_space? %>
              <li>
                <%= link_to t(".inscription", default: "Inscription"), signup_path %>
              </li>
              <li>
                <%= link_to t(".connexion", default: "Connexion"), signin_path %>
              </li>
              <!-- <li>
                <#= link_to t(".espace_pro", default: "Espace Partenaire"), landing_business_path #>
              </li> -->
            <% else %>
              <li>
                <%= link_to t(".inscription", default: "Inscription"), signup_path %>
              </li>
              <li>
                <%= link_to t(".connexion", default: "Connexion"), signin_path %>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </div>
  </nav>

<!-- </div> -->

app/views/layouts/shared/_navbar_logout.html.erb
<nav id="nav">
  <div class="container">
    <div class="nav-items">
      <!-- LOGO LINKS -->
      <div class="nav-left">
        <!-- LOGO -->
        <%= link_to root_path do %>
          <div class="logo-mobile">
            <%= render "components/svg/logo_thumb" %>
          </div>
          <div class="logo-desktop">
            <%= render "components/svg/logo" %>
          </div>
        <% end %>
      </div>
      <!-- SIGNUP/SIGNIN BUTTONS -->
      <div class="nav-right">
      <%= link_to signup_path, class: "sign-up" do %>
        <div class="ripple-area js-ripple">
          <span class="ripple-circle"></span>
        </div>
        Je m'inscris
      <% end %>
      <%= link_to signin_path, class: "sign-in" do %>
        <div class="ripple-area js-ripple">
          <span class="ripple-circle"></span>
        </div>
        Se connecter
      <% end %>
      </div>
    </div>
  </div>

</nav>